In [3]:
# prompt: 請讀取Bakery.csv,並顯示前五筆資料

import pandas as pd

# 假設 Bakery.csv 存在於 Colab 的工作區中
df = pd.read_csv('Bakery.csv')

# 顯示前五筆資料
df.head()

   TransactionNo          Items             DateTime  Daypart  DayType
0              1          Bread  2016-10-30 09:58:11  Morning  Weekend
1              2   Scandinavian  2016-10-30 10:05:34  Morning  Weekend
2              2   Scandinavian  2016-10-30 10:05:34  Morning  Weekend
3              3  Hot chocolate  2016-10-30 10:07:57  Morning  Weekend
4              3            Jam  2016-10-30 10:07:57  Morning  Weekend

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['TransactionNo'].plot(kind='hist', bins=20, title='TransactionNo')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('Items').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby('DateTime').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='index', y='TransactionNo', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Items')):
  _plot_series(series, series_name, i)
  fig.legend(title='Items', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('DateTime')):
  _plot_series(series, series_name, i)
  fig.legend(title='DateTime', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['TransactionNo']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'TransactionNo'}, axis=1)
              .sort_values('TransactionNo', ascending=True))
  xs = counted['TransactionNo']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('TransactionNo', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Items')):
  _plot_series(series, series_name, i)
  fig.legend(title='Items', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('TransactionNo')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['TransactionNo']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'TransactionNo'}, axis=1)
              .sort_values('TransactionNo', ascending=True))
  xs = counted['TransactionNo']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('TransactionNo', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('DateTime')):
  _plot_series(series, series_name, i)
  fig.legend(title='DateTime', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('TransactionNo')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_9['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['TransactionNo'].plot(kind='line', figsize=(8, 4), title='TransactionNo')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['DateTime'].value_counts()
    for x_label, grp in _df_11.groupby('Items')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Items')
_ = plt.ylabel('DateTime')

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_12['Items'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_12, x='index', y='Items', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['DateTime'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='index', y='DateTime', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_14['Items'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_14, x='TransactionNo', y='Items', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['DateTime'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='TransactionNo', y='DateTime', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [4]:
# prompt: 使用 DataFrame df: 請顯示敘述統計

# Display descriptive statistics for numerical columns
df.describe()

       TransactionNo
count   20507.000000
mean     4976.202370
std      2796.203001
min         1.000000
25%      2552.000000
50%      5137.000000
75%      7357.000000
max      9684.000000

In [16]:
# prompt: 請刪除同一個TransactionNo中，重複的items的筆數,刪除後存到新的變數df_g,再保留原本的欄位名稱

df_g = df.groupby(['TransactionNo', 'Items'])['Items'].count().reset_index(name='count')
df_g = df_g.drop_duplicates(subset=['TransactionNo', 'Items'], keep='first')
df_g = df_g[['TransactionNo','Items' , 'count' ]]
df_g

       TransactionNo          Items  count
0                  1          Bread      1
1                  2   Scandinavian      2
2                  3        Cookies      1
3                  3  Hot chocolate      1
4                  3            Jam      1
...              ...            ...    ...
18882           9682   Tacos/Fajita      1
18883           9682            Tea      1
18884           9683         Coffee      1
18885           9683         Pastry      1
18886           9684      Smoothies      1

[18887 rows x 3 columns]

In [19]:
# prompt: 請在一個TransactionNo中，刪除重複的其中一筆資料，刪除後存到新的變數df_g,保留原本的欄位名稱，產生此動作的程式碼即可

df_g = df.drop_duplicates(subset=['TransactionNo', 'Items'], keep='first')
df_g

       TransactionNo          Items             DateTime    Daypart  DayType
0                  1          Bread  2016-10-30 09:58:11    Morning  Weekend
1                  2   Scandinavian  2016-10-30 10:05:34    Morning  Weekend
3                  3  Hot chocolate  2016-10-30 10:07:57    Morning  Weekend
4                  3            Jam  2016-10-30 10:07:57    Morning  Weekend
5                  3        Cookies  2016-10-30 10:07:57    Morning  Weekend
...              ...            ...                  ...        ...      ...
20502           9682         Coffee  2017-09-04 14:32:58  Afternoon  Weekend
20503           9682            Tea  2017-09-04 14:32:58  Afternoon  Weekend
20504           9683         Coffee  2017-09-04 14:57:06  Afternoon  Weekend
20505           9683         Pastry  2017-09-04 14:57:06  Afternoon  Weekend
20506           9684      Smoothies  2017-09-04 15:04:24  Afternoon  Weekend

[18887 rows x 5 columns]

In [20]:
# prompt: 使用 DataFrame df_g: 轉成 Items group by TransactionNo

# Group the dataframe by 'TransactionNo' and aggregate the 'Items' column.
items_by_transaction = df_g.groupby('TransactionNo')['Items'].apply(list)

# Display the result (optional).
items_by_transaction

TransactionNo
1                                                 [Bread]
2                                          [Scandinavian]
3                           [Hot chocolate, Jam, Cookies]
4                                                [Muffin]
5                                 [Coffee, Pastry, Bread]
                              ...
9680                                              [Bread]
9681    [Truffles, Tea, Spanish Brunch, Christmas common]
9682                  [Muffin, Tacos/Fajita, Coffee, Tea]
9683                                     [Coffee, Pastry]
9684                                          [Smoothies]
Name: Items, Length: 9465, dtype: object

In [21]:
# prompt: 請將items_by_transaction的資料轉成one-hot編碼格式 （運用 Transaction Encoder）

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(items_by_transaction).transform(items_by_transaction)
df_onehot = pd.DataFrame(te_ary, columns=te.columns_)
df_onehot

,Adjustment,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Bacon,Baguette,Bakewell,Bare Popcorn,Basket,...,The BART,The Nomad,Tiffin,Toast,Truffles,Tshirt,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9460,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9461,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
9462,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9463,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9464,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [33]:
# prompt: 進行Apriori產生頻繁集，mini support 設定為 0.05

from mlxtend.frequent_patterns import apriori

# 設定最小支持度
min_support = 0.03

# 使用 apriori 函數找出頻繁項目集
frequent_itemsets = apriori(df_onehot, min_support=min_support, use_colnames=True)

# 顯示頻繁項目集
frequent_itemsets

     support             itemsets
0   0.036344          (Alfajores)
1   0.327205              (Bread)
2   0.040042            (Brownie)
3   0.103856               (Cake)
4   0.478394             (Coffee)
5   0.054411            (Cookies)
6   0.039197         (Farm House)
7   0.058320      (Hot chocolate)
8   0.038563              (Juice)
9   0.061807          (Medialuna)
10  0.038457             (Muffin)
11  0.086107             (Pastry)
12  0.071844           (Sandwich)
13  0.034548              (Scone)
14  0.034443               (Soup)
15  0.142631                (Tea)
16  0.033597              (Toast)
17  0.090016      (Coffee, Bread)
18  0.054728       (Cake, Coffee)
19  0.035182  (Medialuna, Coffee)
20  0.047544     (Coffee, Pastry)
21  0.038246   (Sandwich, Coffee)
22  0.049868        (Coffee, Tea)

In [34]:
# prompt: 產生關聯規則，信賴度設定爲0.1

from mlxtend.frequent_patterns import association_rules

# 設定最小信賴度
min_threshold = 0.01

# 使用 association_rules 函數找出關聯規則
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=min_threshold)

# 顯示關聯規則
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Coffee),(Bread),0.478394,0.327205,0.090016,0.188163,0.575059,1.0,-0.066517,0.828731,-0.586210,0.125794,-0.206665,0.231634
1,(Bread),(Coffee),0.327205,0.478394,0.090016,0.275105,0.575059,1.0,-0.066517,0.719561,-0.523431,0.125794,-0.389737,0.231634
2,(Cake),(Coffee),0.103856,0.478394,0.054728,0.526958,1.101515,1.0,0.005044,1.102664,0.102840,0.103745,0.093105,0.320679
3,(Coffee),(Cake),0.478394,0.103856,0.054728,0.114399,1.101515,1.0,0.005044,1.011905,0.176684,0.103745,0.011765,0.320679
4,(Medialuna),(Coffee),0.061807,0.478394,0.035182,0.569231,1.189878,1.0,0.005614,1.210871,0.170091,0.069665,0.174148,0.321387
5,(Coffee),(Medialuna),0.478394,0.061807,0.035182,0.073542,1.189878,1.0,0.005614,1.012667,0.305936,0.069665,0.012509,0.321387
6,(Coffee),(Pastry),0.478394,0.086107,0.047544,0.099382,1.154168,1.0,0.006351,1.014740,0.256084,0.091968,0.014526,0.325764
7,(Pastry),(Coffee),0.086107,0.478394,0.047544,0.552147,1.154168,1.0,0.006351,1.164682,0.146161,0.091968,0.141396,0.325764
8,(Sandwich),(Coffee),0.071844,0.478394,0.038246,0.532353,1.112792,1.0,0.003877,1.115384,0.109205,0.074701,0.103448,0.306150
9,(Coffee),(Sandwich),0.478394,0.071844,0.038246,0.079947,1.112792,1.0,0.003877,1.008807,0.194321,0.074701,0.008731,0.306150
10,(Coffee),(Tea),0.478394,0.142631,0.049868,0.104240,0.730840,1.0,-0.018366,0.957142,-0.413856,0.087310,-0.044777,0.226935
11,(Tea),(Coffee),0.142631,0.478394,0.049868,0.349630,0.730840,1.0,-0.018366,0.802014,-0.300482,0.087310,-0.246862,0.226935

In [35]:
# prompt: 使用 DataFrame rules: 請依照lift由大到小來進行顯示

# Sort the dataframe by the 'lift' column in descending order.
rules_sorted = rules.sort_values('lift', ascending=False)

# Display the sorted dataframe.
rules_sorted

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
5,(Coffee),(Medialuna),0.478394,0.061807,0.035182,0.073542,1.189878,1.0,0.005614,1.012667,0.305936,0.069665,0.012509,0.321387
4,(Medialuna),(Coffee),0.061807,0.478394,0.035182,0.569231,1.189878,1.0,0.005614,1.210871,0.170091,0.069665,0.174148,0.321387
7,(Pastry),(Coffee),0.086107,0.478394,0.047544,0.552147,1.154168,1.0,0.006351,1.164682,0.146161,0.091968,0.141396,0.325764
6,(Coffee),(Pastry),0.478394,0.086107,0.047544,0.099382,1.154168,1.0,0.006351,1.014740,0.256084,0.091968,0.014526,0.325764
8,(Sandwich),(Coffee),0.071844,0.478394,0.038246,0.532353,1.112792,1.0,0.003877,1.115384,0.109205,0.074701,0.103448,0.306150
9,(Coffee),(Sandwich),0.478394,0.071844,0.038246,0.079947,1.112792,1.0,0.003877,1.008807,0.194321,0.074701,0.008731,0.306150
2,(Cake),(Coffee),0.103856,0.478394,0.054728,0.526958,1.101515,1.0,0.005044,1.102664,0.102840,0.103745,0.093105,0.320679
3,(Coffee),(Cake),0.478394,0.103856,0.054728,0.114399,1.101515,1.0,0.005044,1.011905,0.176684,0.103745,0.011765,0.320679
10,(Coffee),(Tea),0.478394,0.142631,0.049868,0.104240,0.730840,1.0,-0.018366,0.957142,-0.413856,0.087310,-0.044777,0.226935
11,(Tea),(Coffee),0.142631,0.478394,0.049868,0.349630,0.730840,1.0,-0.018366,0.802014,-0.300482,0.087310,-0.246862,0.226935
0,(Coffee),(Bread),0.478394,0.327205,0.090016,0.188163,0.575059,1.0,-0.066517,0.828731,-0.586210,0.125794,-0.206665,0.231634
1,(Bread),(Coffee),0.327205,0.478394,0.090016,0.275105,0.575059,1.0,-0.066517,0.719561,-0.523431,0.125794,-0.389737,0.231634

In [36]:
# prompt: 使用 DataFrame rules_sorted: 請匯出成excel

# Export the dataframe to an Excel file
rules_sorted.to_excel('rules_sorted.xlsx', index=False)